### ISSUE TITLE
Revisar documentación para web scraping

### ISSUE THREAD

**Issue by lapicos** [lapicos/vuelafacil#5]
Investigación y análisis del método web scraping para conseguir información de páginas web:

 Documentación.

 Ventajas.

 Desventajas.

 Proceso.

Tipos.

 Librerías.

**Comment by jaens0324** [comment]
> Investigación y análisis del método web scraping para conseguir información de páginas web:
> 
> Documentación.
> 
> Ventajas.
> 
> Desventajas.
> 
> Proceso.
> 
> Tipos.
> 
> Librerías.

**Comment by jaens0324** [comment]
[Informe_webscraping.docx](https://github.com/lapicos/vuelafacil/files/7181864/Informe_webscraping.docx)
A continuación adjunto entrega de Informe de investigación y análisis del método WEB-SCRAPING para extraer información de sitios web

**Comment by lapicos** [comment]
Actividad completada
