### ISSUE TITLE
Propuesta estructura inicial de base de datos

### ISSUE THREAD

**Issue by lapicos** [lapicos/vuelafacil#6]
Esta tarea ejecutara el análisis de las necesidades en cuanto al almacenamiento de información en varios aspectos del proyecto, y buscara la manera de solucionar este requerimiento entregando una propuesta a implementar.

**Comment by yershony** [comment]
En este espacio realizo la entrega para el sprint2 
[Propuesta base de datos.pdf](https://github.com/lapicos/vuelafacil/files/7181815/Propuesta.base.de.datos.pdf)
